// Generated by void migrate.
import { defineConfig } from 'void/config';

export default defineConfig({
  "inference": {
    "build": "nuxt build",
    "scanDirs": [
      "app",
      "server",
      "db",
      "shared"
    ]
  },
  "worker": {
    "compatibility_date": "2025-12-21",
    "compatibility_flags": [
      "nodejs_compat"
    ]
  },
  "cloudflare": {
    "account_id": "4e2a0666763dd77021727233a9031482",
    "compatibility_date": "2026-02-24"
  }
});
